export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      restaurant_settings: { Row: { id:string; nome:string; logo_url:string|null; cor_primaria:string|null; cor_primaria_dark:string|null; cor_secundaria:string|null; cor_background:string|null; taxa_base_entrega:number; valor_minimo_pedido:number; chave_pix:string|null; whatsapp:string|null; tempo_estimado:string|null; horario_funcionamento:Json; criado_em:string; atualizado_em:string }; Insert: Partial<Database["public"]["Tables"]["restaurant_settings"]["Row"]> & { nome?:string }; Update: Partial<Database["public"]["Tables"]["restaurant_settings"]["Row"]> };
      categories: { Row:{id:string;nome:string;ordem:number;ativo:boolean;criado_em:string;atualizado_em:string}; Insert:Partial<Database["public"]["Tables"]["categories"]["Row"]> & {nome:string}; Update:Partial<Database["public"]["Tables"]["categories"]["Row"]> };
      products: { Row:{id:string;category_id:string;nome:string;descricao:string|null;preco:number;imagem_url:string|null;ativo:boolean;destaque:boolean;criado_em:string;atualizado_em:string}; Insert:Partial<Database["public"]["Tables"]["products"]["Row"]> & {category_id:string;nome:string;preco:number}; Update:Partial<Database["public"]["Tables"]["products"]["Row"]> };
      option_groups: { Row:{id:string;product_id:string;nome:string;min_select:number;max_select:number;obrigatorio:boolean;ordem:number}; Insert:Partial<Database["public"]["Tables"]["option_groups"]["Row"]> & {product_id:string;nome:string}; Update:Partial<Database["public"]["Tables"]["option_groups"]["Row"]> };
      options: { Row:{id:string;group_id:string;nome:string;preco_extra:number;ordem:number;ativo:boolean}; Insert:Partial<Database["public"]["Tables"]["options"]["Row"]> & {group_id:string;nome:string}; Update:Partial<Database["public"]["Tables"]["options"]["Row"]> };
      addons: { Row:{id:string;nome:string;preco:number;ativo:boolean;criado_em:string;atualizado_em:string}; Insert:Partial<Database["public"]["Tables"]["addons"]["Row"]> & {nome:string;preco:number}; Update:Partial<Database["public"]["Tables"]["addons"]["Row"]> };
      product_addons: { Row:{product_id:string;addon_id:string}; Insert:Database["public"]["Tables"]["product_addons"]["Row"]; Update:Partial<Database["public"]["Tables"]["product_addons"]["Row"]> };
      customers: { Row:{id:string;user_id:string;nome:string;telefone:string;criado_em:string;atualizado_em:string}; Insert:Partial<Database["public"]["Tables"]["customers"]["Row"]> & {user_id:string;nome:string;telefone:string}; Update:Partial<Database["public"]["Tables"]["customers"]["Row"]> };
      addresses: { Row:{id:string;customer_id:string;rotulo:string|null;rua:string;numero:string;complemento:string|null;bairro:string;cidade:string;cep:string;referencia:string|null;lat:number|null;lng:number|null;padrao:boolean;criado_em:string;atualizado_em:string}; Insert:Partial<Database["public"]["Tables"]["addresses"]["Row"]> & {customer_id:string;rua:string;numero:string;bairro:string;cidade:string;cep:string}; Update:Partial<Database["public"]["Tables"]["addresses"]["Row"]> };
      delivery_zones: { Row:{id:string;nome:string;taxa:number;ativo:boolean;criado_em:string;atualizado_em:string}; Insert:Partial<Database["public"]["Tables"]["delivery_zones"]["Row"]> & {nome:string;taxa:number}; Update:Partial<Database["public"]["Tables"]["delivery_zones"]["Row"]> };
      coupons: { Row:{id:string;codigo:string;tipo:"percentual"|"fixo";valor:number;pedido_minimo:number;limite_usos:number|null;usos_atuais:number;validade:string|null;ativo:boolean;criado_em:string;atualizado_em:string}; Insert:Partial<Database["public"]["Tables"]["coupons"]["Row"]> & {codigo:string;tipo:"percentual"|"fixo";valor:number}; Update:Partial<Database["public"]["Tables"]["coupons"]["Row"]> };
      orders: { Row:{id:string;customer_id:string;address_id:string|null;status:"recebido"|"preparando"|"saiu_para_entrega"|"entregue"|"cancelado";subtotal:number;taxa_entrega:number;desconto:number;total:number;forma_pagamento:"pix"|"cartao"|"na_entrega";status_pagamento:"pendente"|"confirmado"|"falhou";coupon_id:string|null;observacoes:string|null;criado_em:string;atualizado_em:string}; Insert:Partial<Database["public"]["Tables"]["orders"]["Row"]> & {customer_id:string;subtotal:number;total:number;forma_pagamento:"pix"|"cartao"|"na_entrega"}; Update:Partial<Database["public"]["Tables"]["orders"]["Row"]> };
      order_items: { Row:{id:string;order_id:string;product_id:string|null;quantidade:number;preco_unitario:number;opcoes_selecionadas:Json;adicionais_selecionados:Json;observacao_item:string|null}; Insert:Partial<Database["public"]["Tables"]["order_items"]["Row"]> & {order_id:string;quantidade:number;preco_unitario:number}; Update:Partial<Database["public"]["Tables"]["order_items"]["Row"]> };
      order_status_history: { Row:{id:string;order_id:string;status:"recebido"|"preparando"|"saiu_para_entrega"|"entregue"|"cancelado";motivo_cancelamento:string|null;alterado_em:string}; Insert:Partial<Database["public"]["Tables"]["order_status_history"]["Row"]> & {order_id:string;status:Database["public"]["Tables"]["order_status_history"]["Row"]["status"]}; Update:Partial<Database["public"]["Tables"]["order_status_history"]["Row"]> };
      payments: { Row:{id:string;order_id:string;mp_payment_id:string|null;status:"pendente"|"confirmado"|"falhou";qr_code:string|null;qr_code_base64:string|null;valor:number;criado_em:string;atualizado_em:string}; Insert:Partial<Database["public"]["Tables"]["payments"]["Row"]> & {order_id:string;valor:number}; Update:Partial<Database["public"]["Tables"]["payments"]["Row"]> };
      admin_users: { Row:{id:string;user_id:string;nome:string;papel:"admin"|"atendente";criado_em:string}; Insert:Partial<Database["public"]["Tables"]["admin_users"]["Row"]> & {user_id:string;nome:string;papel:"admin"|"atendente"}; Update:Partial<Database["public"]["Tables"]["admin_users"]["Row"]> };
    };
    Functions: { validar_cupom: { Args:{codigo:string;valor_pedido:number}; Returns:{valido:boolean;tipo:string;valor:number;desconto:number}[] } };
  };
}
