"use client";
import { useEffect,useState,useTransition } from "react";
import { createClient } from "@/lib/supabase/client";
import { setOrderStatus } from "@/server/actions/admin-orders";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
type Status="recebido"|"preparando"|"saiu_para_entrega"|"entregue"|"cancelado";type Row={id:string;status:Status;status_pagamento:string;total:number;criado_em:string;customer:{nome:string;telefone:string}|null};
const columns:Status[]=["recebido","preparando","saiu_para_entrega","entregue","cancelado"];const labels:Record<Status,string>={recebido:"Recebido",preparando:"Preparando",saiu_para_entrega:"Saiu para entrega",entregue:"Entregue",cancelado:"Cancelado"};
export function OrdersBoard({initial}:{initial:Row[]}){const [orders,setOrders]=useState(initial);const [pending,startTransition]=useTransition();useEffect(()=>{const supabase=createClient();const channel=supabase.channel("admin-orders").on("postgres_changes",{event:"*",schema:"public",table:"orders"},payload=>setOrders(current=>{const next=payload.eventType==="INSERT"?[payload.new as Row,...current]:current.map(o=>o.id===(payload.new as Row).id?{...o,...payload.new}:o);return next})).subscribe();return()=>{void supabase.removeChannel(channel)}},[]);const move=(id:string,status:Status)=>startTransition(async()=>{const r=await setOrderStatus(id,status,status==="cancelado"?window.prompt("Motivo do cancelamento")||"":undefined);if(!r.ok)window.alert(r.message)});return <div className="mt-6 grid gap-4 xl:grid-cols-5">{columns.map(status=><section key={status} className="min-w-0"><div className="mb-3 flex items-center justify-between"><h2 className="font-bold">{labels[status]}</h2><span className="text-xs opacity-55">{orders.filter(o=>o.status===status).length}</span></div><div className="grid gap-3">{orders.filter(o=>o.status===status).map(order=><Card key={order.id} className={order.status_pagamento!=="confirmado"?"opacity-55":""}><div className="flex justify-between gap-3"><div><p className="font-bold">#{order.id.slice(0,8)}</p><p className="text-sm">{order.customer?.nome||"Cliente"}</p></div><Badge status={status==="saiu_para_entrega"?"saiu":status}>{order.status_pagamento==="confirmado"?labels[status]:"Aguardando pagamento"}</Badge></div><p className="mt-3 text-xs opacity-55">{new Date(order.criado_em).toLocaleString("pt-BR")}</p><div className="mt-2 flex items-center justify-between"><span className="font-bold">R$ {Number(order.total).toFixed(2).replace(".",",")}</span>{order.status_pagamento==="confirmado"&&status!=="entregue"&&status!=="cancelado"&&<Button size="sm" disabled={pending} onClick={()=>move(order.id,status==="recebido"?"preparando":status==="preparando"?"saiu_para_entrega":"entregue")}>Avançar</Button>}</div>{status!=="recebido"&&status!=="cancelado"&&<Button className="mt-2 w-full" size="sm" variant="ghost" onClick={()=>move(order.id,"cancelado")}>Cancelar</Button>}</Card>)}</div></section>)}</div>}
