"use server";import { revalidatePath } from "next/cache";import { createClient } from "@/lib/supabase/server";import { createAdminClient } from "@/lib/supabase/admin";import { requireAdmin } from "@/server/admin";async function guard(){const a=await requireAdmin();if(!a||a.admin.papel!=="admin")throw new Error("Não autorizado.");return createClient();}
export async function saveCategory(i:{id?:string;nome:string;ordem:number;ativo:boolean}){const db=await guard();if(!i.nome.trim())return {ok:false,message:"Nome obrigatório."};const q=i.id?db.from("categories").update({nome:i.nome.trim(),ordem:i.ordem,ativo:i.ativo}).eq("id",i.id):db.from("categories").insert({nome:i.nome.trim(),ordem:i.ordem,ativo:i.ativo});const {error}=await q;if(error)return {ok:false,message:error.message};revalidatePath("/");return {ok:true};}
export async function saveProduct(i:{id?:string;category_id:string;nome:string;descricao?:string;preco:number;imagem_url?:string|null;ativo:boolean;destaque:boolean}){const db=await guard();if(!i.nome.trim()||i.preco<0)return {ok:false,message:"Nome e preço válidos são obrigatórios."};const p={category_id:i.category_id,nome:i.nome.trim(),descricao:i.descricao?.trim()||null,preco:i.preco,imagem_url:i.imagem_url||null,ativo:i.ativo,destaque:i.destaque};const q=i.id?db.from("products").update(p).eq("id",i.id):db.from("products").insert(p);const {error}=await q;if(error)return {ok:false,message:error.message};revalidatePath("/");return {ok:true};}
export async function toggleProduct(id:string,ativo:boolean){const db=await guard();const {error}=await db.from("products").update({ativo}).eq("id",id);if(error)return {ok:false,message:error.message};revalidatePath("/");return {ok:true};}
export async function deleteProduct(id:string){const db=await guard();const {error}=await db.from("products").delete().eq("id",id);if(error)return {ok:false,message:error.message};revalidatePath("/");return {ok:true};}
export async function saveOptionGroup(i:{id?:string;product_id:string;nome:string;min_select:number;max_select:number;obrigatorio:boolean;ordem:number}){const db=await guard();if(!i.nome.trim()||i.min_select<0||i.max_select<i.min_select)return {ok:false,message:"Grupo inválido."};const p={product_id:i.product_id,nome:i.nome.trim(),min_select:i.min_select,max_select:i.max_select,obrigatorio:i.obrigatorio,ordem:i.ordem};const q=i.id?db.from("option_groups").update(p).eq("id",i.id):db.from("option_groups").insert(p);const {error}=await q;if(error)return {ok:false,message:error.message};revalidatePath("/");return {ok:true};}
export async function saveOption(i:{id?:string;group_id:string;nome:string;preco_extra:number;ordem:number;ativo:boolean}){const db=await guard();if(!i.nome.trim()||i.preco_extra<0)return {ok:false,message:"Opção inválida."};const p={group_id:i.group_id,nome:i.nome.trim(),preco_extra:i.preco_extra,ordem:i.ordem,ativo:i.ativo};const q=i.id?db.from("options").update(p).eq("id",i.id):db.from("options").insert(p);const {error}=await q;if(error)return {ok:false,message:error.message};revalidatePath("/");return {ok:true};}
export async function saveAddon(i:{id?:string;nome:string;preco:number;ativo:boolean}){const db=await guard();if(!i.nome.trim()||i.preco<0)return {ok:false,message:"Adicional inválido."};const p={nome:i.nome.trim(),preco:i.preco,ativo:i.ativo};const q=i.id?db.from("addons").update(p).eq("id",i.id):db.from("addons").insert(p);const {error}=await q;if(error)return {ok:false,message:error.message};revalidatePath("/");return {ok:true};}
export async function linkAddon(productId:string,addonId:string){const db=await guard();const {error}=await db.from("product_addons").upsert({product_id:productId,addon_id:addonId});if(error)return {ok:false,message:error.message};revalidatePath("/");return {ok:true};}
export async function unlinkAddon(productId:string,addonId:string){const db=await guard();const {error}=await db.from("product_addons").delete().eq("product_id",productId).eq("addon_id",addonId);if(error)return {ok:false,message:error.message};revalidatePath("/");return {ok:true};}
export async function uploadProductImage(formData:FormData){await guard();const file=formData.get("file");const productId=formData.get("productId");if(!(file instanceof File)||typeof productId!=="string")return {ok:false,message:"Arquivo inválido."};if(file.size>5*1024*1024||!file.type.startsWith("image/"))return {ok:false,message:"Imagem inválida (máximo 5MB)."};const admin=createAdminClient();await admin.storage.createBucket("product-images",{public:true}).catch(()=>undefined);const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${productId}/${crypto.randomUUID()}.${ext}`;const up=await admin.storage.from("product-images").upload(path,file,{contentType:file.type,upsert:false});if(up.error)return {ok:false,message:up.error.message};const url=admin.storage.from("product-images").getPublicUrl(path).data.publicUrl;const db=await createClient();const {error}=await db.from("products").update({imagem_url:url}).eq("id",productId);if(error)return {ok:false,message:error.message};revalidatePath("/");return {ok:true,url};}
