"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireAdmin } from "@/server/admin";

async function guard(){const auth=await requireAdmin();if(!auth||auth.admin.papel!=="admin")throw new Error("Não autorizado.");return createClient();}
export async function saveCategory(i:{id?:string;nome:string;ordem:number;ativo:boolean}){const db=await guard();if(!i.nome.trim()||!Number.isInteger(i.ordem)||i.ordem<0)return{ok:false,message:"Categoria inválida."};const q=i.id?db.from("categories").update({nome:i.nome.trim(),ordem:i.ordem,ativo:i.ativo}).eq("id",i.id):db.from("categories").insert({nome:i.nome.trim(),ordem:i.ordem,ativo:i.ativo});const{error}=await q;if(error)return{ok:false,message:"Não foi possível salvar a categoria."};revalidatePath("/");revalidatePath("/admin/cardapio");return{ok:true};}
export async function deleteCategory(id:string){const db=await guard();const{data:products}=await db.from("products").select("id").eq("category_id",id).limit(1);if(products?.length)return{ok:false,message:"Não exclua uma categoria com produtos. Mova os produtos primeiro."};const{error}=await db.from("categories").delete().eq("id",id);if(error)return{ok:false,message:"Não foi possível excluir a categoria."};revalidatePath("/");return{ok:true};}
export async function saveProduct(i:{id?:string;category_id:string;nome:string;descricao?:string;preco:number;imagem_url?:string|null;ativo:boolean;destaque:boolean}){const db=await guard();if(!i.category_id||!i.nome.trim()||!Number.isFinite(i.preco)||i.preco<0)return{ok:false,message:"Nome, categoria e preço válidos são obrigatórios."};const{data:category}=await db.from("categories").select("id").eq("id",i.category_id).maybeSingle();if(!category)return{ok:false,message:"Categoria inválida."};const p={category_id:i.category_id,nome:i.nome.trim(),descricao:i.descricao?.trim()||null,preco:i.preco,imagem_url:i.imagem_url?.trim()||null,ativo:i.ativo,destaque:i.destaque};
 if(i.id){const{error}=await db.from("products").update(p).eq("id",i.id);if(error)return{ok:false,message:"Não foi possível salvar o produto."};revalidatePath("/");revalidatePath("/admin/cardapio");return{ok:true,id:i.id};}
 const{data,error}=await db.from("products").insert(p).select("id").single();if(error||!data)return{ok:false,message:"Não foi possível salvar o produto."};revalidatePath("/");revalidatePath("/admin/cardapio");return{ok:true,id:data.id};}
export async function toggleProduct(id:string,ativo:boolean){const db=await guard();const{error}=await db.from("products").update({ativo}).eq("id",id);if(error)return{ok:false,message:"Não foi possível alterar a disponibilidade do produto."};revalidatePath("/");return{ok:true};}
export async function deleteProduct(id:string){const db=await guard();const{error}=await db.from("products").delete().eq("id",id);if(error)return{ok:false,message:"Não foi possível excluir o produto."};revalidatePath("/");return{ok:true};}
export async function saveOptionGroup(i:{id?:string;product_id:string;nome:string;min_select:number;max_select:number;obrigatorio:boolean;ordem:number}){const db=await guard();if(!i.product_id||!i.nome.trim()||!Number.isInteger(i.min_select)||!Number.isInteger(i.max_select)||i.min_select<0||i.max_select<i.min_select||!Number.isInteger(i.ordem)||i.ordem<0)return{ok:false,message:"Grupo inválido."};const{data:product}=await db.from("products").select("id").eq("id",i.product_id).maybeSingle();if(!product)return{ok:false,message:"Produto inválido."};const p={product_id:i.product_id,nome:i.nome.trim(),min_select:i.min_select,max_select:i.max_select,obrigatorio:i.obrigatorio,ordem:i.ordem};const q=i.id?db.from("option_groups").update(p).eq("id",i.id):db.from("option_groups").insert(p);const{error}=await q;if(error)return{ok:false,message:"Não foi possível salvar o grupo."};revalidatePath("/");return{ok:true};}
export async function deleteOptionGroup(id:string){const db=await guard();const{error}=await db.from("option_groups").delete().eq("id",id);if(error)return{ok:false,message:"Não foi possível excluir o grupo."};revalidatePath("/");return{ok:true};}
export async function saveOption(i:{id?:string;group_id:string;nome:string;preco_extra:number;ordem:number;ativo:boolean}){const db=await guard();if(!i.group_id||!i.nome.trim()||!Number.isFinite(i.preco_extra)||i.preco_extra<0||!Number.isInteger(i.ordem)||i.ordem<0)return{ok:false,message:"Opção inválida."};const{data:group}=await db.from("option_groups").select("id").eq("id",i.group_id).maybeSingle();if(!group)return{ok:false,message:"Grupo inválido."};const p={group_id:i.group_id,nome:i.nome.trim(),preco_extra:i.preco_extra,ordem:i.ordem,ativo:i.ativo};const q=i.id?db.from("options").update(p).eq("id",i.id):db.from("options").insert(p);const{error}=await q;if(error)return{ok:false,message:"Não foi possível salvar a opção."};revalidatePath("/");return{ok:true};}
export async function deleteOption(id:string){const db=await guard();const{error}=await db.from("options").delete().eq("id",id);if(error)return{ok:false,message:"Não foi possível excluir a opção."};revalidatePath("/");return{ok:true};}
export async function saveAddon(i:{id?:string;nome:string;preco:number;ativo:boolean}){const db=await guard();if(!i.nome.trim()||!Number.isFinite(i.preco)||i.preco<0)return{ok:false,message:"Adicional inválido."};const p={nome:i.nome.trim(),preco:i.preco,ativo:i.ativo};const q=i.id?db.from("addons").update(p).eq("id",i.id):db.from("addons").insert(p);const{error}=await q;if(error)return{ok:false,message:"Não foi possível salvar o adicional."};revalidatePath("/");return{ok:true};}
export async function deleteAddon(id:string){const db=await guard();const{error:linkError}=await db.from("product_addons").delete().eq("addon_id",id);if(linkError)return{ok:false,message:"Não foi possível remover os vínculos do adicional."};const{error}=await db.from("addons").delete().eq("id",id);if(error)return{ok:false,message:"Não foi possível excluir o adicional."};revalidatePath("/");return{ok:true};}
export async function linkAddon(productId:string,addonId:string){const db=await guard();const[{data:product},{data:addon}]=await Promise.all([db.from("products").select("id").eq("id",productId).maybeSingle(),db.from("addons").select("id").eq("id",addonId).maybeSingle()]);if(!product||!addon)return{ok:false,message:"Produto ou adicional inválido."};const{error}=await db.from("product_addons").upsert({product_id:productId,addon_id:addonId});if(error)return{ok:false,message:"Não foi possível associar o adicional."};revalidatePath("/");return{ok:true};}
export async function unlinkAddon(productId:string,addonId:string){const db=await guard();const{error}=await db.from("product_addons").delete().eq("product_id",productId).eq("addon_id",addonId);if(error)return{ok:false,message:"Não foi possível remover o vínculo."};revalidatePath("/");return{ok:true};}
export async function uploadProductImage(formData:FormData){const db=await guard();const file=formData.get("file");const productId=formData.get("productId");if(!(file instanceof File)||typeof productId!=="string")return{ok:false,message:"Arquivo inválido."};const{data:product}=await db.from("products").select("id").eq("id",productId).maybeSingle();if(!product)return{ok:false,message:"Produto inválido."};const allowed=new Set(["image/png","image/jpeg","image/webp"]);if(!allowed.has(file.type)||file.size>5*1024*1024)return{ok:false,message:"Imagem inválida. Use PNG, JPEG ou WEBP com até 5 MB."};const admin=createAdminClient();const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${productId}/${crypto.randomUUID()}.${ext}`;const up=await admin.storage.from("product-images").upload(path,file,{contentType:file.type,upsert:false});if(up.error)return{ok:false,message:"Não foi possível enviar a imagem."};const url=admin.storage.from("product-images").getPublicUrl(path).data.publicUrl;const{error}=await db.from("products").update({imagem_url:url}).eq("id",productId);if(error)return{ok:false,message:"Imagem enviada, mas não foi possível vinculá-la ao produto."};revalidatePath("/");revalidatePath("/admin/cardapio");return{ok:true,url};}
