"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireAdmin } from "@/server/admin";

async function db(){const a=await requireAdmin();if(!a||a.admin.papel!=="admin")throw new Error("Não autorizado.");return createClient();}

export async function saveCoupon(i:{id?:string;codigo:string;tipo:"percentual"|"fixo";valor:number;pedido_minimo:number;limite_usos:number|null;validade:string|null;ativo:boolean}){const s=await db();if(!i.codigo.trim()||i.valor<0||i.pedido_minimo<0||(i.tipo==="percentual"&&i.valor>100))return {ok:false,message:"Dados inválidos."};const p={codigo:i.codigo.trim().toUpperCase(),tipo:i.tipo,valor:i.valor,pedido_minimo:i.pedido_minimo,limite_usos:i.limite_usos,validade:i.validade||null,ativo:i.ativo};const q=i.id?s.from("coupons").update(p).eq("id",i.id):s.from("coupons").insert(p);const {error}=await q;if(error)return {ok:false,message:error.message};revalidatePath("/admin/cupons");return {ok:true};}
export async function saveDeliveryZone(i:{id?:string;nome:string;taxa:number;ativo:boolean}){const s=await db();if(!i.nome.trim()||i.taxa<0)return {ok:false,message:"Zona inválida."};const q=i.id?s.from("delivery_zones").update({nome:i.nome.trim(),taxa:i.taxa,ativo:i.ativo}).eq("id",i.id):s.from("delivery_zones").insert({nome:i.nome.trim(),taxa:i.taxa,ativo:i.ativo});const {error}=await q;if(error)return {ok:false,message:error.message};revalidatePath("/admin/zonas-de-entrega");return {ok:true};}
export async function saveRestaurantSettings(i:{nome:string;logo_url?:string;taxa_base_entrega:number;valor_minimo_pedido:number;chave_pix?:string;whatsapp?:string;tempo_estimado?:string;horario_funcionamento:Record<string,{abertura:string;fechamento:string;ativo:boolean}>}){const s=await db();if(!i.nome.trim()||i.taxa_base_entrega<0||i.valor_minimo_pedido<0)return {ok:false,message:"Configuração inválida."};const {data:cur}=await s.from("restaurant_settings").select("id").limit(1).maybeSingle();const p={nome:i.nome.trim(),logo_url:i.logo_url?.trim()||null,taxa_base_entrega:i.taxa_base_entrega,valor_minimo_pedido:i.valor_minimo_pedido,chave_pix:i.chave_pix?.trim()||null,whatsapp:i.whatsapp?.trim()||null,tempo_estimado:i.tempo_estimado?.trim()||null,horario_funcionamento:i.horario_funcionamento};const q=cur?s.from("restaurant_settings").update(p).eq("id",cur.id):s.from("restaurant_settings").insert(p);const {error}=await q;if(error)return {ok:false,message:error.message};revalidatePath("/");revalidatePath("/admin/configuracoes");return {ok:true};}

export async function uploadRestaurantLogo(formData:FormData){await db();const file=formData.get("file");if(!(file instanceof File))return{ok:false,message:"Arquivo inválido."};if(file.size>5*1024*1024||!file.type.startsWith("image/"))return{ok:false,message:"Logo inválida (máximo 5MB)."};const admin=createAdminClient();await admin.storage.createBucket("restaurant-assets",{public:true}).catch(()=>undefined);const ext=file.name.split(".").pop()?.toLowerCase()||"png";const path=`branding/logo-${crypto.randomUUID()}.${ext}`;const upload=await admin.storage.from("restaurant-assets").upload(path,file,{contentType:file.type,upsert:false});if(upload.error)return{ok:false,message:upload.error.message};const url=admin.storage.from("restaurant-assets").getPublicUrl(path).data.publicUrl;const s=await db();const{data:cur}=await s.from("restaurant_settings").select("id").limit(1).maybeSingle();const result=cur?await s.from("restaurant_settings").update({logo_url:url}).eq("id",cur.id):await s.from("restaurant_settings").insert({nome:"Tabajara's Churrascaria",logo_url:url});if(result.error)return{ok:false,message:result.error.message};revalidatePath("/");revalidatePath("/admin/configuracoes");return{ok:true,url};}
