"use client";
import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { BottomSheet } from "@/components/ui/bottom-sheet";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Logo } from "@/components/ui/logo";
import { RadioGroup } from "@/components/ui/radio-group";
import { Select } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { ToastProvider, useToast } from "@/components/ui/toast";
function Preview(){const [dialog,setDialog]=useState(false);const [sheet,setSheet]=useState(false);const [radio,setRadio]=useState("a");const {show}=useToast();return <main className="mx-auto max-w-5xl p-6 md:p-10"><header className="rounded-2xl bg-[var(--color-secondary)] p-6 text-white"><div className="flex items-center gap-4"><Logo size={72}/><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--color-primary)]">Tabajara's</p><h1 className="mt-1 text-2xl font-extrabold uppercase tracking-wide">Churrascaria</h1></div></div></header><div className="mt-8 grid gap-5 md:grid-cols-2"><Card><h2 className="font-semibold">Botões</h2><div className="mt-4 flex flex-wrap gap-2"><Button size="sm">Primário</Button><Button variant="secondary" size="sm">Secundário</Button><Button variant="outline" size="sm">Contorno</Button><Button variant="ghost" size="sm">Ghost</Button><Button variant="destructive" size="sm">Destrutivo</Button></div></Card><Card><h2 className="font-semibold">Formulários</h2><div className="mt-4 grid gap-3"><Input placeholder="Nome"/><Textarea placeholder="Observação"/><Select defaultValue="a"><option value="a">Opção A</option><option value="b">Opção B</option></Select><label className="flex items-center gap-2 text-sm"><Checkbox/> Aceito os termos</label><RadioGroup name="demo" value={radio} onChange={setRadio} options={[{value:"a",label:"Escolha A"},{value:"b",label:"Escolha B"}]}/></div></Card><Card><h2 className="font-semibold">Status</h2><div className="mt-4 flex flex-wrap gap-2"><Badge status="recebido">Recebido</Badge><Badge status="preparando">Preparando</Badge><Badge status="saiu">Saiu para entrega</Badge><Badge status="entregue">Entregue</Badge><Badge status="cancelado">Cancelado</Badge></div></Card><Card><h2 className="font-semibold">Overlays</h2><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" onClick={()=>setDialog(true)}>Abrir Dialog</Button><Button size="sm" variant="outline" onClick={()=>setSheet(true)}>Abrir BottomSheet</Button><Button size="sm" variant="secondary" onClick={()=>show("Notificação de teste","success")}>Mostrar Toast</Button></div></Card><Card><h2 className="font-semibold">Logo</h2><div className="mt-4 flex items-center gap-6"><Logo size={48}/><Logo size={72}/><Logo size={110}/></div></Card><Card><h2 className="font-semibold">Carregamento</h2><div className="mt-4 space-y-2"><Skeleton className="h-4 w-2/3"/><Skeleton className="h-10 w-full"/></div></Card></div><Dialog open={dialog} onClose={()=>setDialog(false)} title="Dialog de demonstração"><p className="text-sm opacity-70">Componente pronto para uso nas próximas etapas.</p><div className="mt-5"><Button onClick={()=>setDialog(false)}>Fechar</Button></div></Dialog><BottomSheet open={sheet} onClose={()=>setSheet(false)} title="BottomSheet de demonstração"><p className="text-sm opacity-70">Área inferior confortável para mobile.</p></BottomSheet></main>}
export default function StyleGuide(){return <ToastProvider><Preview/></ToastProvider>}
